% 21-sept-2013
% Exploración del primer micro conjunto de datos que tenemos de pepsi.
% Makefile: 

Archivos
--------------------------------------------------------------------------------------------------
- Dcd : Info de clientes. 99+1 variables
- Indcli: Archivo resumen del cliente en el día. 32+1 variables
- Indpro: Archivo x producto, x cliente, x ruta de las cosas vendidas o no. Este es el archivo +imp. 17+1 cols
- Indtie: Info de las horas. 7+1 campos

Indpro
--------------------------------------------------------------------------------------------------

En este archivo están las ventas o no-ventas por producto. R sí cacha bien las 18 columnas, que son:

Nombre original | Nombre nuestro  | Descripción
--------------- | --------------- | ----------------------------
PRO_CLAVE       | prod.id         |   clave del producto
CLI_CLAVE	      | cliente.id      |   clave del cliente corporativa
RUT_CLAVE	      | ruta.id         |   clave de ruta corporativa
ID_SUC	        | centro.id       |   sucursal corporativa
FECHA_TRANS	    | fecha.trans     |   fecha de la transacción (cuando le venden papitas)
FECHA_CARGA	    | fecha.carga     |   fecha en que se esta realizando la carga (cuando sale camionetita)
COM_CLAVE	      | cia.id          |   clave de compañía INASE: sabritas, quaker...
DHP_IMPORTE	    | vta.impo        |   Venta Real  importe
DHP_UNIDADES	  | vta.units       |   Venta Real unidades
BAN_VTA	        | dummy.vta       |   Bandera que indica si el producto tuvo venta o no
DHP_INVINI	    | invent.0        |   Inventario Inicial
DHP_UNIDEV	    | u.devol         |   Unidades devueltas
DHP_UNIROT	    | u.rot           |   Unidades rotadas
DHP_UNICAP	    | u.capt          |   Unidades Capturadas
DHP_UNISUG	    | u.sug           |   Unidades Sugeridas
DHP_UNIFAL	    | u.falt          |   Unidades Faltantes
DHP_PRECTE	    | precio          |   Precio Cliente



```{r,eval=FALSE}
setwd("/Users/PandoraMac/Documents/David/pepsi2/Datos_R/")
nombres<-c("carpeta","prod.id","cliente.id","ruta.id","centro.id","fecha.trans","fecha.carga","cia.id","vta.imp","vta.units","dummy.vta","invent.0","u.devol","u.rot","u.capt","u.sug", "u.falt","precio")
s<-as.data.frame(read.table("R_indpro.txt.mod", sep="|",header=FALSE,
                            colClasses=c(rep("character",8),"numeric",rep("integer",8),"numeric")))
names(s)<-nombres
head(s)

   carpeta prod.id cliente.id ruta.id centro.id fecha.trans fecha.carga cia.id vta.imp vta.units dummy.vta
1 A3490435  695012 I000015919    0001       349  2013-04-18  2013-04-18     30   17.52         3         1
2 A3490435  065713 I000015919    0001       349  2013-04-18  2013-04-18     30   10.84         2         1
3 A3490435  017315 I000015919    0001       349  2013-04-18  2013-04-18     30   16.26         3         1
4 A3490435  583201 I000015919    0001       349  2013-04-18  2013-04-18     30    6.09         1         1
5 A3490435  357231 I000015919    0001       349  2013-04-18  2013-04-18     30    5.83         1         1
6 A3490435  637023 I000015919    0001       349  2013-04-18  2013-04-18     30   12.50         2         1
  invent.0 u.devol u.rot u.capt u.sug u.falt precio
1       NA       0     0      3     0      0   5.84
2       NA       0     0      2     0      0   5.42
3       NA       0     0      3     0      0   5.42
4       NA       0     0      1     0      0   6.09
5       NA       0     0      1     0      0   5.83
6       NA       0     0      2     0      0   6.25
```



